@baseUrl1 = http://localhost:4004


### metadata for all entity expose in AdmineService
GET {{baseUrl1}}/admin/$metadata

### Get all Sap_Module
GET {{baseUrl1}}/admin/ModuleSRV

### Get all Employees
GET {{baseUrl1}}/admin/employeesSRV

###
GET {{baseUrl1}}/admin/employeesSRV?$filter=sapmodule eq 'ABAP'

### Get all Upskills_emp
GET {{baseUrl1}}/admin/zupskills_empSRV

### Get all Upskills_emp
GET {{baseUrl1}}/admin/zupskills_empSRV?$filter=id eq '1' or id eq '10'

###
GET {{baseUrl1}}/admin/zupskills_empSRV?$filter=trainingid eq 'T001'


### Insert Upskilling Record
POST {{baseUrl1}}/admin/Insert_upskillsSRV
Content-Type: application/json

{
  "id": "1",
  "trainingid": "T021",
  "trainingname": "CAPM Advanced Concepts",
  "numberofdays": 6,
  "startdate": "2025-08-15",
  "completiondate": "2025-08-21",
  "status": "Planned"
}

### Insert Upskilling Record
POST {{baseUrl1}}/admin/Insert_upskillsSRV1
Content-Type: application/json

{
  "id": "2",
  "trainingid": "T023",
  "trainingname": "CAPM Advanced Concepts",
  "numberofdays": 6,
  "startdate": "2025-08-15",
  "completiondate": "2025-08-21",
  "status": "Planned"
}


### Update Upskills Record
POST http://localhost:4004/admin/Update_upskillsSRV
Content-Type: application/json

{
  "id": "1",
  "trainingid": "T021",
  "trainingname": "CAPM Deep Dive",
  "numberofdays": 7,
  "startdate": "2025-08-20",
  "completiondate": "2025-08-27",
  "status": "Ongoing"
}

### Update Upskills Record
POST http://localhost:4004/admin/Update_upskillsSRV1
Content-Type: application/json

{
  "id": "1",
  "trainingid": "T021",
  "trainingname": "CAPM Deep Dive",
  "numberofdays": 17,
  "startdate": "2025-08-20",
  "completiondate": "2025-08-27",
  "status": "Ongoing"
}


### Delete Upskills Record
POST http://localhost:4004/admin/Delete_upskillsSRV
Content-Type: application/json

{
  "id": "1",
  "trainingid": "T021"
}


### Delete Upskills Record
POST http://localhost:4004/admin/Delete_upskillsSRV1
Content-Type: application/json

{
  "id": "1",
  "trainingid": "T021"
}